export enum CenterEffectType {
    SmilePrincess = 1,
    PureAngel = 2,
    CoolEmpress = 3,
    PurePrincess = 112,
    CoolPrincess = 113,
    SmileAngel = 121,
    CoolAngel = 123,
    SmileEmpress = 131,
    PureEmpress = 132,
}

export enum CenterApplyType {
    FirstYear = 1,
    SecondYear = 2,
    ThirdYear = 3,
    Muse = 4,
    Aqours = 5,
    Printemps = 6,
    LilyWhite = 7,
    BiBi = 8,
    CYaRon = 9,
    AZALEA = 10,
    GuiltyKiss = 11,
    Nijigasaki = 60,
    HonokaEli = 71,
    HonokaKotori = 72,
    HonokaUmi = 73,
    HonokaRin = 74,
    HonokaMaki = 75,
    HonokaNozomi = 76,
    HonokaHanayo = 77,
    HonokaNico = 78,
    EliKotori = 79,
    EliUmi = 80,
    EliRin = 81,
    EliMaki = 82,
    EliNozomi = 83,
    EliHanayo = 84,
    EliNico = 85,
    KotoriUmi = 86,
    KotoriRin = 87,
    KotoriMaki = 88,
    KotoriNozomi = 89,
    KotoriHanayo = 90,
    KotoriNico = 91,
    UmiRin = 92,
    UmiMaki = 93,
    UmiNozomi = 94,
    UmiHanayo = 95,
    UmiNico = 96,
    RinMaki = 97,
    RinNozomi = 98,
    RinHanayo = 99,
    RinNico = 100,
    MakiNozomi = 101,
    MakiHanayo = 102,
    MakiNico = 103,
    NozomiHanayo = 104,
    NozomiNico = 105,
    HanayoNico = 106,
    ChikaRiko = 107,
    ChikaKanan = 108,
    ChikaDia = 109,
    ChikaYou = 110,
    ChikaYoshiko = 111,
    ChikaHanamaru = 112,
    ChikaMari = 113,
    ChikaRuby = 114,
    RikoKanan = 115,
    RikoDia = 116,
    RikoYou = 117,
    RikoYoshiko = 118,
    RikoHanamaru = 119,
    RikoMari = 120,
    RikoRuby = 121,
    KananDia = 122,
    KananYou = 123,
    KananYoshiko = 124,
    KananHanamaru = 125,
    KananMari = 126,
    KananRuby = 127,
    DiaYou = 128,
    DiaYoshiko = 129,
    DiaHanamaru = 130,
    DiaMari = 131,
    DiaRuby = 132,
    YouYoshiko = 133,
    YouHanamaru = 134,
    YouMari = 135,
    YouRuby = 136,
    YoshikoHanamaru = 137,
    YoshikoMari = 138,
    YoshikoRuby = 139,
    HanamaruMari = 140,
    HanamaruRuby = 141,
    MariRuby = 142,
    Liella = 143,
}

export type CenterSkill = {
    main: {
        type: CenterEffectType
        value: number
    }
    extra: {
        apply?: CenterApplyType
        type?: CenterEffectType
        value?: number
    }
} | null
