name: Update

on:
  schedule:
    - cron: '30 7 * * *'
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      - id: update
        run: |
          echo 'result<<EOF' >> $GITHUB_OUTPUT
          npm run update >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Updated database
          title: Updated database
          body: |
            ```
            ${{ steps.update.outputs.result }}
            ```
